### PR TITLE
chore: update to dawn v15

### PR DESCRIPTION
**Pull request by tomheaton**
[SPARK-5509](https://app.clickup.com/t/4558226/SPARK-5509)

### CODE REVIEW

**Comment by timmw** [comment]
Quite hard to review these dawn updates. Did you encounter any merge conflicts? Those are generally where issues may arise. I'll give this a test on my store

**Comment by timmw** [comment]
Looking good overall, just found one issue on product page
> Liquid error (sections/main-product line 493): Could not find asset snippets/product-variant-picker.liquid
image
Guess v15 removes or renames that file

**Comment by tomheaton** [comment]
i think my latest change just fixed that
image

**Comment by tomheaton** [comment]
have checked a full checkout, nothing out of the ordinary (however my experience with "ordinary" is quite little)

**Review by timmw — APPROVED** [review]

**Review by cm-sl — APPROVED** [review]

**Review by cm-sl — APPROVED** [review]

**Pull request merged**
